### ISSUE TITLE
Add a basic VM analysis tool to VManalyze

### ISSUE THREAD

**Issue by R3x** [teambi0s/secREtary#18]
This tool must be able to 

- [ ] Dump switch cases
- [ ] Figure out how many times each switch case is hit when run with a given input

**Comment by pranjalsingh008** [comment]
@Freakston Add me

**Comment by Freakston** [comment]
Adding Initial skeleton code which can find the offset of the switch statement.

TODO : 

- [x] Frequency of each statement.
- [x] Offset of cases hit.

**Comment by Freakston** [comment]
Finish implementing the module.

- [x] Frequency of each statement.
- [x] Offset of cases hit.

**Comment by Freakston** [comment]
@akulpillai @sandrabeme Can you guys review the PR #26

**Comment by akulpillai** [comment]
PR looks good, merged.
